### ISSUE TITLE
Better localization support

### ISSUE THREAD

**Issue by nyuwec** [philbooth/vagueTime.js#21]
In some languages future and past tenses expressed differently. For example in Hungarian "2 days ago" translates to "2 napja", but "in 2 days" translates to "2 nap múlva". As you can see the words must be separated more, please check the implementation is moment.js: https://github.com/moment/moment/blob/develop/locale/en-gb.js
It handles singular, plural, past and future as separate cases. But it is far from easy to translate, because as a translator you should understand the javascript code.

I would create a simple "matrix" containing all the strings with placeholders inside, so the translators could freely write the proper sentences.
```
translations = {
...
'day': {
  'singular': {
    'past': 'one minute ago',
    'future': 'in a minute'
  },
  'plural': {
    'past': '%d minutes ago',
    'future': 'in %d minutes'
  },
...
},
```

wdyt?

**Comment by philbooth** [comment]
> wdyt?

I think it's an excellent suggestion, thanks. I'm happy to accept a pull request or make one myself when I get some time.

But also, fwiw, I'm a little bit uneasy about this library doing any translation at all, for the reasons your suggestion highlights. It requires a dedicated translation solution to get this stuff right, and the presence of translation here is purely the result of gradual creep as PRs came in one-by-one. Maybe it would be better to revert this library to the much simpler, single-language state that it used to be in before languages were added?

Or maybe not, I'm undecided. :confused:

**Comment by nyuwec** [comment]
Meanwhile I rewrote your lib in TypeScript and I created a simpler localisation solution. It has a flat object for every language. AFAIK this is the most usable format, for example this way it could be easily transformed into gettext PO or any other solution.

Here is the language object for 'en' and 'hu':
```
		private static languages = {
			en: {
				'VAGUETIME_YEAR_SINGULAR_PAST': 'one year ago',
				'VAGUETIME_YEAR_SINGULAR_FUTURE': 'in a year',
				'VAGUETIME_YEAR_PLURAL_PAST': '%d years ago',
				'VAGUETIME_YEAR_PLURAL_FUTURE': 'in %d years',
				'VAGUETIME_MONTH_SINGULAR_PAST': 'one month ago',
				'VAGUETIME_MONTH_SINGULAR_FUTURE': 'in a month',
				'VAGUETIME_MONTH_PLURAL_PAST': '%d months ago',
				'VAGUETIME_MONTH_PLURAL_FUTURE': 'in %d months',
				'VAGUETIME_WEEK_SINGULAR_PAST': 'one week ago',
				'VAGUETIME_WEEK_SINGULAR_FUTURE': 'in a week',
				'VAGUETIME_WEEK_PLURAL_PAST': '%d weeks ago',
				'VAGUETIME_WEEK_PLURAL_FUTURE': 'in %d weeks',
				'VAGUETIME_DAY_SINGULAR_PAST': 'one day ago',
				'VAGUETIME_DAY_SINGULAR_FUTURE': 'in a day',
				'VAGUETIME_DAY_PLURAL_PAST': '%d days ago',
				'VAGUETIME_DAY_PLURAL_FUTURE': 'in %d days',
				'VAGUETIME_HOUR_SINGULAR_PAST': 'one hour ago',
				'VAGUETIME_HOUR_SINGULAR_FUTURE': 'in an hour',
				'VAGUETIME_HOUR_PLURAL_PAST': '%d hours ago',
				'VAGUETIME_HOUR_PLURAL_FUTURE': 'in %d hours',
				'VAGUETIME_MINUTE_SINGULAR_PAST': 'one minute ago',
				'VAGUETIME_MINUTE_SINGULAR_FUTURE': 'in a minute',
				'VAGUETIME_MINUTE_PLURAL_PAST': '%d minutes ago',
				'VAGUETIME_MINUTE_PLURAL_FUTURE': 'in %d minutes',
				'VAGUETIME_DEFAULT_PAST': 'just now',
				'VAGUETIME_DEFAULT_FUTURE': 'soon'
			},
			hu: {
				'VAGUETIME_YEAR_SINGULAR_PAST': 'egy éve',
				'VAGUETIME_YEAR_SINGULAR_FUTURE': 'egy éven belül',
				'VAGUETIME_YEAR_PLURAL_PAST': '%d éve',
				'VAGUETIME_YEAR_PLURAL_FUTURE': '%d éven belül',
				'VAGUETIME_MONTH_SINGULAR_PAST': 'egy hónapja',
				'VAGUETIME_MONTH_SINGULAR_FUTURE': 'egy hónapon belül',
				'VAGUETIME_MONTH_PLURAL_PAST': '%d hónapja',
				'VAGUETIME_MONTH_PLURAL_FUTURE': '%d hónapon belül',
				'VAGUETIME_WEEK_SINGULAR_PAST': 'egy hete',
				'VAGUETIME_WEEK_SINGULAR_FUTURE': 'egy héten belül',
				'VAGUETIME_WEEK_PLURAL_PAST': '%d hete',
				'VAGUETIME_WEEK_PLURAL_FUTURE': '%d héten belül',
				'VAGUETIME_DAY_SINGULAR_PAST': 'egy napja',
				'VAGUETIME_DAY_SINGULAR_FUTURE': 'egy napon belül',
				'VAGUETIME_DAY_PLURAL_PAST': '%d napja',
				'VAGUETIME_DAY_PLURAL_FUTURE': '%d napon belül',
				'VAGUETIME_HOUR_SINGULAR_PAST': 'egy órája',
				'VAGUETIME_HOUR_SINGULAR_FUTURE': 'egy órán belül',
				'VAGUETIME_HOUR_PLURAL_PAST': '%d órája',
				'VAGUETIME_HOUR_PLURAL_FUTURE': '%d órán belül',
				'VAGUETIME_MINUTE_SINGULAR_PAST': 'egy perce',
				'VAGUETIME_MINUTE_SINGULAR_FUTURE': 'egy percen belül',
				'VAGUETIME_MINUTE_PLURAL_PAST': '%d perce',
				'VAGUETIME_MINUTE_PLURAL_FUTURE': '%d percen belül',
                'VAGUETIME_DEFAULT_PAST': 'most',
				'VAGUETIME_DEFAULT_FUTURE': 'hamarosan'
			}
		};
```

with this function I can generate the proper key:
```
		private static createI18nKey(timeStep:string, isPast: boolean, isSingular?: boolean) {
			var singularStr = "_";
			if (isSingular != null) {
				singularStr = (isSingular ? '_SINGULAR_' : '_PLURAL_');
			}
			return PreziVagueTimeModule.i18nPrefix + timeStep.toUpperCase() + singularStr + (isPast?'PAST':'FUTURE');
		}
```

example calls in estimate():
1. calling defaults for past/future:
```
return lang[PreziVagueTimeModule.createI18nKey('default', isPast)];
```
2. calling when it finds a proper interval:
```
return lang[PreziVagueTimeModule.createI18nKey(timeStep, isPast, isSingular)].replace('%d', vagueTime);
```

My idea is to refactor the language object to separate files and the build or a wrapper could create/inject the proper list of translation templates.

**Comment by philbooth** [comment]
Fyi, I've decided to remove the translation stuff completely on the grounds that it will never be as good as a dedicated l10n solution, so is unjustifiable complexity. Closing this issue.
